# Source: tekton-pipeline/templates/tekton-container-registry-auth-secret.yaml
apiVersion: v1
data:
  .dockerconfigjson: ""
kind: Secret
metadata:
  name: tekton-container-registry-auth
  namespace: tekton-pipelines
  annotations:
    tekton.dev/docker-0:
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pipelines
    gitops.jenkins-x.io/pipeline: 'namespaces'
type: kubernetes.io/dockerconfigjson
