# Source: tekton-pipeline/templates/tekton-container-registry-auth-secret.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: tekton-container-registry-auth
  namespace: tekton-pipelines
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pipelines
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  backendType: gcpSecretsManager
  projectId: jenkins-x-labs-bdd
  data:
    - name: .dockerconfigjson
      key: jstrachan-catalog-tekton-container-registry-auth
      version: latest
  template:
    metadata:
      annotations:
        tekton.dev/docker-0:
      labels:
        app.kubernetes.io/component: webhook
        app.kubernetes.io/instance: default
        app.kubernetes.io/part-of: tekton-pipelines
    type: kubernetes.io/dockerconfigjson
