# Source: jxboot-helmfile-resources/templates/docker-cfg-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: jenkins-docker-cfg
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
type: Opaque
data:
  config.json: "e30="
