# Source: jxboot-helmfile-resources/templates/npm-token-secret.yaml
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: jenkins-npm-token
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
data:
  token: ""
