# Source: jxboot-helmfile-resources/templates/release-gpg-secret.yaml
apiVersion: v1
data:
  pubring.gpg: ""
  sec-jenkins.gpg: ""
  secring.gpg: ""
  trustdb.gpg: ""
kind: Secret
metadata:
  name: jenkins-release-gpg
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
type: Opaque
