# Source: jxboot-helmfile-resources/templates/jx-basic-auth-secret.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: jx-basic-auth
  namespace: jx
  annotations:
    secret.jenkins-x.io/schema-object: '{"name":"jx-basic-auth","properties":[{"name":"auth","question":"the htpasswd format basic auth for Ingress","help":"The htpassord encoded user and password for basic auth ingresses"}],"mandatory":true}'
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  backendType: gcpSecretsManager
  projectId: jenkins-x-labs-bdd
  data:
    - name: auth
      key: jstrachan-catalog-jx-basic-auth
      version: latest
  template:
    type: Opaque
    metadata:
      annotations:
        secret.jenkins-x.io/schema-object: '{"name":"jx-basic-auth","properties":[{"name":"auth","question":"the htpasswd format basic auth for Ingress","help":"The htpassord encoded user and password for basic auth ingresses"}],"mandatory":true}'
