# Source: jxboot-helmfile-resources/templates/tekton-git-secret.yaml
apiVersion: v1
data:
  password: "ZHVtbXlwd2Q="
  username: "ZHVtbXl1c2Vy"
kind: Secret
metadata:
  name: tekton-git
  annotations:
    tekton.dev/git-0: "https://github.com"
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pipelines
    gitops.jenkins-x.io/pipeline: 'namespaces'
  namespace: jx
type: kubernetes.io/basic-auth
