# Source: jxboot-helmfile-resources/templates/tekton-git-secret.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: tekton-git
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pipelines
    gitops.jenkins-x.io/pipeline: 'namespaces'
  namespace: jx
spec:
  backendType: gcpSecretsManager
  projectId: jenkins-x-labs-bdd
  data:
    - name: password
      key: jstrachan-catalog-jx-pipeline-user
      property: token
      version: latest
    - name: username
      key: jstrachan-catalog-jx-pipeline-user
      property: username
      version: latest
  template:
    metadata:
      annotations:
        tekton.dev/git-0: "https://github.com"
      labels:
        app.kubernetes.io/component: controller
        app.kubernetes.io/instance: default
        app.kubernetes.io/part-of: tekton-pipelines
    type: kubernetes.io/basic-auth
