environments:
  # The "default" environment is available and used when `helmfile` is run without `--environment NAME`.
  #
  # these values are available to any values.yaml.gotmpl files but they are not passed into 
  # the helm charts directly
  default:
    values:
    - jx-values.yaml
    - versionStream/src/fake-secrets.yaml.gotmpl
releases:
- chart: jenkins-x/jxboot-helmfile-resources
- chart: external-secrets/kubernetes-external-secrets
- chart: jx-labs/jenkins-x-crds
- chart: jx3/jx-preview
- chart: stable/nginx-ingress
- chart: jenkins-x/tekton
- chart: jenkins-x/lighthouse
- chart: jenkins-x/nexus
- chart: jenkins-x/chartmuseum
- chart: jx-labs/pusher-wave