filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
    - versionStream/src/fake-secrets.yaml.gotmpl
repositories:
- name: jenkins-x
  url: https://storage.googleapis.com/chartmuseum.jenkins-x.io
- name: external-secrets
  url: https://godaddy.github.io/kubernetes-external-secrets
- name: jx-labs
  url: https://storage.googleapis.com/jenkinsxio-labs-private/charts
- name: jx3
  url: https://storage.googleapis.com/jenkinsxio/charts
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com
- name: cdf
  url: https://cdfoundation.github.io/tekton-helm-chart
- name: dev
  url: http://chartmuseum-jx.34.66.77.190.nip.io/
releases:
- chart: jenkins-x/jxboot-helmfile-resources
  version: 0.0.307
  name: jxboot-helmfile-resources
  namespace: jx
  values:
  - versionStream/charts/jenkins-x/jxboot-helmfile-resources/values.yaml.gotmpl
  - charts/jenkins-x/jxboot-helmfile-resources/values.yaml.gotmpl
- chart: external-secrets/kubernetes-external-secrets
  version: 5.2.0
  name: kubernetes-external-secrets
  namespace: secret-infra
  values:
  - versionStream/charts/external-secrets/kubernetes-external-secrets/values.yaml.gotmpl
- chart: jx-labs/jenkins-x-crds
  version: 0.0.7
  name: jenkins-x-crds
  namespace: jx
  values:
  - versionStream/charts/jx-labs/jenkins-x-crds/values.yaml
- chart: jx3/jx-preview
  name: jx-preview
  namespace: jx
- chart: stable/nginx-ingress
  version: 1.39.1
  name: nginx-ingress
  namespace: nginx
  values:
  - versionStream/charts/stable/nginx-ingress/values.yaml.gotmpl
- chart: cdf/tekton-pipeline
  version: 0.0.2
  name: tekton
  namespace: tekton-pipelines
  values:
  - versionStream/charts/cdf/tekton-pipeline/values.yaml.gotmpl
- chart: jenkins-x/lighthouse
  version: 0.0.831
  name: lighthouse
  namespace: jx
  values:
  - versionStream/charts/jenkins-x/lighthouse/values.yaml.gotmpl
  - charts/jenkins-x/lighthouse/values.yaml.gotmpl
- chart: jenkins-x/nexus
  version: 0.1.35
  name: nexus
  namespace: jx
  values:
  - versionStream/charts/jenkins-x/nexus/values.yaml.gotmpl
- chart: jenkins-x/chartmuseum
  version: 1.1.7
  name: chartmuseum
  namespace: jx
  values:
  - versionStream/charts/jenkins-x/chartmuseum/values.yaml.gotmpl
- chart: jx-labs/pusher-wave
  version: 1.0.0
  name: pusher-wave
  namespace: secret-infra
- chart: dev/nodey510
  version: 1.0.88
  name: nodey510
  namespace: jx-production
templates: {}
missingFileHandler: ""
