jxRequirements:
  autoUpdate:
    enabled: false
    schedule: ""
  bootConfigURL: https://github.com/jenkins-x/jx3-boot-config
  buildPacks:
    buildPackLibrary:
      gitRef: master
      gitURL: https://github.com/jenkins-x/jx3-pipeline-catalog.git
  cluster:
    clusterName: jstrachan-catalog2
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    gke:
      projectNumber: "688875092189"
    namespace: jx
    project: jenkins-x-labs-bdd
    provider: gke
    registry: gcr.io
    zone: us-central1-a
  environments:
  - ingress:
      domain: 34.66.77.190.nip.io
      externalDNS: false
      namespaceSubDomain: -jx.
      tls:
        email: ""
        enabled: false
        production: true
    key: dev
    owner: jstrachan
    repository: jx3-demo-catalog-dev
  - ingress:
      domain: ""
      externalDNS: false
      namespaceSubDomain: ""
      tls:
        email: ""
        enabled: false
        production: false
    key: staging
    promotionStrategy: Auto
  - ingress:
      domain: ""
      externalDNS: false
      namespaceSubDomain: ""
      tls:
        email: ""
        enabled: false
        production: false
    key: production
    promotionStrategy: Auto
  gitops: true
  ingress:
    domain: 34.66.77.190.nip.io
    externalDNS: false
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: true
  kaniko: true
  pipelineUser:
    username: jstrachan
  repository: nexus
  secretStorage: gsm
  storage:
    backup:
      enabled: false
      url: ""
    logs:
      enabled: true
      url: gs://logs-jstrachan-catalog2-fbe7043249e4
    reports:
      enabled: true
      url: gs://reports-jstrachan-catalog2-fbe7043249e4
    repository:
      enabled: true
      url: gs://repository-jstrachan-catalog2-fbe7043249e4
  vault: {}
  velero:
    schedule: ""
    ttl: ""
  versionStream:
    ref: master
    url: https://github.com/jenkins-x/jxr-versions.git
  webhook: lighthouse
