# Source: nodey400/templates/release.yaml
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2020-09-29T16:48:28Z"
  deletionTimestamp: null
  name: 'nodey400-0.0.18'
  namespace: jx-staging
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  commits:
    - author:
        accountReference:
          - id: jstrachan-0
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: jstrachan
      branch: master
      committer:
        accountReference:
          - id: jstrachan-0
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: jstrachan
      message: |
        release 0.0.18
      sha: d1527230d49f84d9ad06b3af875a3c05e9f36e6f
  gitCloneUrl: https://github.com/jstrachan/nodey400.git
  gitHttpUrl: https://github.com/jstrachan/nodey400
  gitOwner: jstrachan
  gitRepository: nodey400
  name: 'nodey400'
  releaseNotesURL: https://github.com/jstrachan/nodey400/releases/tag/v0.0.18
  version: v0.0.18
status: {}
