# Source: nodey530/templates/release.yaml
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2020-10-07T10:35:32Z"
  deletionTimestamp: null
  name: 'nodey530-1.0.11'
  namespace: jx-staging
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  commits:
    - author:
        accountReference:
          - id: jstrachan-0
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: jstrachan
      branch: master
      committer:
        accountReference:
          - id: jstrachan-0
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: jstrachan
      message: |
        release 1.0.11
      sha: 25779aa566b2b52fe81bca0a8ff88fa141da8222
    - author:
        accountReference:
          - id: jstrachan-0
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: jstrachan
      branch: master
      committer:
        accountReference:
          - id: jstrachan-0
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: jstrachan
      message: |
        release 1.0.11
      sha: aac0ace5a20ec94577a53c020c3b3fccd9e59ebf
    - author:
        accountReference:
          - id: jstrachan-0
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: jstrachan
      branch: master
      committer:
        accountReference:
          - id: jstrachan-0
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: jstrachan
      message: |
        added variables
      sha: fb26d569401efcb0a87ba3322206fa86678c9f32
    - author:
        accountReference:
          - id: james-strachan-0
            provider: jenkins.io/git-github-userid
        email: james.strachan@gmail.com
        name: James Strachan
      branch: master
      committer:
        accountReference:
          - id: github-0
            provider: jenkins.io/git-github-userid
        email: noreply@github.com
        name: GitHub
      message: Update index.html
      sha: 7d21ed3effd83542760026a42bc879872dc8424b
  gitCloneUrl: https://github.com/jstrachan/nodey530.git
  gitHttpUrl: https://github.com/jstrachan/nodey530
  gitOwner: jstrachan
  gitRepository: nodey530
  name: 'nodey530'
  releaseNotesURL: https://github.com/jstrachan/nodey530/releases/tag/v1.0.11
  version: v1.0.11
status: {}
