apiVersion: v1
data:
  config.yaml: |
    branch-protection:
      orgs:
        jstrachan:
          repos:
            nodey400:
              required_status_checks:
                contexts:
                - pr-build
      protect-tested-repos: true
    github:
      LinkURL: null
    in_repo_config:
      enabled:
        '*': true
    plank: {}
    pod_namespace: jx
    postsubmits:
      jstrachan/nodey400:
      - agent: tekton
        branches:
        - master
        name: release
      jstrachan/nodey500:
      - agent: tekton
        branches:
        - master
        name: release
        pipeline_run_spec:
          pipelineRef:
            name: jx-meta-pipeline
    presubmits:
      jstrachan/nodey400:
      - agent: tekton
        always_run: true
        context: pr-build
        name: pr-build
        rerun_command: /test this
        trigger: (?m)^/test( all| this),?(\s+|$)
      jstrachan/nodey500:
      - agent: tekton
        always_run: true
        context: pr-build
        name: pr-build
        pipeline_run_spec:
          pipelineRef:
            name: jx-meta-pipeline
        rerun_command: /test this
        trigger: (?m)^/test( all| this),?(\s+|$)
    prowjob_namespace: jx
    push_gateway:
      serve_metrics: false
    tide:
      context_options:
        from-branch-protection: true
        required-if-present-contexts: null
        skip-unknown-contexts: false
      merge_method:
        jstrachan/jx3-demo-catalog-dev: merge
        jstrachan/nodey400: merge
        jstrachan/nodey500: merge
        jstrachan/nodey510: merge
      queries:
      - labels:
        - approved
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - jstrachan/nodey400
        - jstrachan/nodey500
      - labels:
        - updatebot
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - jstrachan/nodey400
        - jstrachan/nodey500
      target_url: http://deck-jx.-jx.34.66.77.190.nip.io
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
