apiVersion: jenkins.io/v1
kind: Scheduler
metadata:
  creationTimestamp: null
  name: jx-meta-pipeline
spec:
  approve:
    issueRequired: false
    lgtmActsAsApprove: true
    requireSelfApproval: true
  merger:
    blockerLabel: ""
    maxGoroutines: 0
    mergeMethod: merge
    policy:
      fromBranchProtection: true
      optionalContexts: {}
      requiredContexts: {}
      requiredIfPresentContexts: {}
      skipUnknownContexts: false
    prStatusBaseUrl: ""
    squashLabel: ""
  plugins:
    entries:
    - approve
    - assign
    - blunderbuss
    - help
    - hold
    - lgtm
    - lifecycle
    - override
    - size
    - trigger
    - wip
    - heart
    - cat
    - dog
    - pony
  policy:
    protectTested: true
  postsubmits:
    entries:
    - agent: tekton
      branches:
        entries:
        - master
      cluster: ""
      context: ""
      labels: {}
      maxConcurrency: 0
      name: release
      report: false
      runIfChanged: ""
      skipBranches: {}
      pipeline_run_spec:
        params:
        - description: git url to clone
          name: REPO_URL
          type: string
        - default: master
          description: git revision to checkout (branch, tag, sha, ref…)
          name: revision
          type: string
        - default: source
          description: subdirectory inside of /workspace to clone the git repo
          name: subdirectory
          type: string
        pipelineRef:
          name: jx-meta-pipeline

  presubmits:
    entries:
    - agent: tekton
      alwaysRun: true
      branches: {}
      cluster: ""
      context: pr-build
      labels: {}
      maxConcurrency: 0
      mergeMethod: ""
      name: pr-build
      optional: false
      pipeline_run_spec:
        params:
        - description: git url to clone
          name: REPO_URL
          type: string
        - default: master
          description: git revision to checkout (branch, tag, sha, ref…)
          name: revision
          type: string
        - default: source
          description: subdirectory inside of /workspace to clone the git repo
          name: subdirectory
          type: string
        pipelineRef:
          name: jx-meta-pipeline
      policy:
        Replace: false
        requiredStatusChecks:
          contexts:
            entries:
            - pr-build
      queries:
      - excludedBranches: {}
        includedBranches: {}
        labels:
          entries:
          - approved
        milestone: ""
        missingLabels:
          entries:
          - do-not-merge
          - do-not-merge/hold
          - do-not-merge/work-in-progress
          - needs-ok-to-test
          - needs-rebase
        reviewApprovedRequired: false
      - excludedBranches: {}
        includedBranches: {}
        labels:
          entries:
          - updatebot
        milestone: ""
        missingLabels:
          entries:
          - do-not-merge
          - do-not-merge/hold
          - do-not-merge/work-in-progress
          - needs-ok-to-test
          - needs-rebase
        reviewApprovedRequired: false
      report: true
      rerunCommand: /test this
      runIfChanged: ""
      skipBranches: {}
      trigger: (?m)^/test( all| this),?(\s+|$)
  schedulerAgent:
    agent: tekton
  trigger:
    ignoreOkToTest: false
    joinOrgUrl: ""
    onlyOrgMembers: false
  welcome:
  - message_template: Welcome
