# Source: nodey400/templates/release.yaml
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2020-09-29T14:30:44Z"
  deletionTimestamp: null
  name: 'nodey400-0.0.14'
  namespace: jx-production
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  commits:
    - author:
        accountReference:
          - id: jstrachan-0
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: jstrachan
      branch: master
      committer:
        accountReference:
          - id: jstrachan-0
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: jstrachan
      message: |
        release 0.0.14
      sha: 2cce2e5b15bb48fa3987eccbe0bdcdb9724efac0
  gitCloneUrl: https://github.com/jstrachan/nodey400.git
  gitHttpUrl: https://github.com/jstrachan/nodey400
  gitOwner: jstrachan
  gitRepository: nodey400
  name: 'nodey400'
  releaseNotesURL: https://github.com/jstrachan/nodey400/releases/tag/v0.0.14
  version: v0.0.14
status: {}
