# Source: nexus/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: nexus
  labels:
    app: nexus-nexus
    chart: "nexus-0.1.35"
    release: "nexus"
    heritage: "Helm"
    gitops.jenkins-x.io/pipeline: 'namespaces'
  namespace: jx
type: Opaque
data:
  password: "dG9kbw=="
