metadata:
  creationTimestamp: null
spec:
  groups:
  - owner: jstrachan
    scheduler: in-repo
    repositories:
    - name: nodey510
    - name: nodey500
      scheduler: jx-meta-pipeline
    - name: nodey400
      scheduler: default
