apiVersion: gitops.jenkins-x.io/v1alpha1
kind: SourceConfig
metadata:
  creationTimestamp: null
spec:
  groups:
  - owner: jstrachan
    repositories:
    - name: nodey400
      scheduler: jx-meta-pipeline
    - name: nodey510
    scheduler: in-repo
  - owner: jstrachan
    provider: https://github.com
    providerKind: github
    repositories:
    - name: demo301
      scheduler: in-repo
    - name: nodey530
      scheduler: jx-meta-pipeline
    - name: nodey531
      scheduler: in-repo
    - name: nodey532
      scheduler: in-repo
