# Source: nodey510/templates/release.yaml
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2020-09-27T11:50:29Z"
  deletionTimestamp: null
  name: 'nodey510-1.0.86'
  namespace: jx-staging
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  commits:
    - author:
        accountReference:
          - id: jstrachan-0
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: jstrachan
      branch: master
      committer:
        accountReference:
          - id: jstrachan-0
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: jstrachan
      message: |
        release 1.0.86
      sha: e4ee2ca5afdd1a321376e83e3c041b9c1b7cbe7c
    - author:
        accountReference:
          - id: james-strachan-0
            provider: jenkins.io/git-github-userid
        email: james.strachan@gmail.com
        name: James Strachan
      branch: master
      committer:
        accountReference:
          - id: james-strachan-0
            provider: jenkins.io/git-github-userid
        email: james.strachan@gmail.com
        name: James Strachan
      message: |
        fix: update page
      sha: 8489d028dbafb19fda886c5d605cabdf5177b755
  gitCloneUrl: https://github.com/jstrachan/nodey510.git
  gitHttpUrl: https://github.com/jstrachan/nodey510
  gitOwner: jstrachan
  gitRepository: nodey510
  name: 'nodey510'
  releaseNotesURL: https://github.com/jstrachan/nodey510/releases/tag/v
  version: v
status: {}
