# Source: nodey510/templates/release.yaml
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2020-09-25T13:35:06Z"
  deletionTimestamp: null
  name: 'nodey510-1.0.63'
  namespace: jx-staging
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  commits:
    - author:
        accountReference:
          - id: jstrachan-0
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: jstrachan
      branch: master
      committer:
        accountReference:
          - id: jstrachan-0
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: jstrachan
      message: |
        release 1.0.63
      sha: 44bd95296ce763acd36274633ba6a8fe06a823b8
    - author:
        accountReference:
          - id: james-strachan-0
            provider: jenkins.io/git-github-userid
        email: james.strachan@gmail.com
        name: James Strachan
      branch: master
      committer:
        accountReference:
          - id: james-strachan-0
            provider: jenkins.io/git-github-userid
        email: james.strachan@gmail.com
        name: James Strachan
      message: |
        fix: version
      sha: b9f2c37508b069818ead784e6eb636bfbd688800
  gitCloneUrl: https://github.com/jstrachan/nodey510.git
  gitHttpUrl: https://github.com/jstrachan/nodey510
  gitOwner: jstrachan
  gitRepository: nodey510
  name: 'nodey510'
  releaseNotesURL: https://github.com/jstrachan/nodey510/releases/tag/v0.0.1
  version: v0.0.1
status: {}
