# Source: lighthouse/templates/webhooks-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lighthouse-webhooks
  labels:
    draft: draft-app
    chart: "lighthouse-0.0.827"
    app: lighthouse-webhooks
    gitops.jenkins-x.io/pipeline: 'namespaces'
  annotations:
    checksum/config: b866a8551cd684743d843058fcbf005c2792e590f4989d22e3ecbcad2a98758a
    wave.pusher.com/update-on-config-change: 'true'
    jenkins-x.io/hash: '053713b87e836ef22acb2dbaf0f2a8eb78c00034936d474e2e78613e5a60cb78'
  namespace: jx
spec:
  replicas: 2
  selector:
    matchLabels:
      draft: draft-app
      app: lighthouse-webhooks
  template:
    metadata:
      labels:
        draft: draft-app
        app: lighthouse-webhooks
    spec:
      serviceAccountName: lighthouse-webhooks
      containers:
        - name: lighthouse-webhooks
          image: gcr.io/jenkinsxio/lighthouse-webhooks:0.0.0-SNAPSHOT-PR-1072-17
          imagePullPolicy: IfNotPresent
          args:
            - "--namespace=jx"
          env:
            - name: "GIT_KIND"
              value: "github"
            - name: "GIT_SERVER"
              value: "https://github.com"
            - name: "GIT_USER"
              value: jstrachan
            - name: "GIT_TOKEN"
              valueFrom:
                secretKeyRef:
                  name: lighthouse-oauth-token
                  key: oauth
            - name: "HMAC_TOKEN"
              valueFrom:
                secretKeyRef:
                  name: "lighthouse-hmac-token"
                  key: hmac
            - name: "JX_LOG_FORMAT"
              value: "json"
            - name: "LOGRUS_FORMAT"
              value: "json"
            - name: JX_DEFAULT_IMAGE
              value: "gcr.io/jenkinsxio/builder-maven:2.1.142-761"
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 80m
              memory: 128Mi
      terminationGracePeriodSeconds: 180
