# Source: lighthouse/templates/jenkins-controller-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: lighthouse-jenkins-token
  labels:
    app: lighthouse-lighthouse
    chart: "lighthouse-0.0.843"
    release: "lighthouse"
    heritage: "Helm"
    gitops.jenkins-x.io/pipeline: 'namespaces'
  namespace: jx
type: Opaque
data:
  token: ""
